title: F de FÃ­sica
description: Hola
theme: just-the-docs

logo: "/assets/images/logo3.png"
favicon_ico: "/assets/images/icon1.png"

compress_html:
  blanklines: true

callouts:
  nota:
    title: Nota
    color: purple

